# detect params
confidence_thres: 0.15
nms_thres: 0.3
device: 'gpu'  # cpu
auto_choose_device: true
input_size: 640
fp16: false

# weight file

weight_size: 's'  # m,l,x,tiny
model_path: './best.pth'
is_trt_file: false
classes_file: 'visimple.txt'

# input source

source: '/home/uagv/dataset/visdrone/coco/val'        #  0      'assets/dog.jpg'   '/path/to/your/image_dir'
source_type: 'image_dir'        # 'cam'   'image'            'image_dir'
save_image: false
show_image: true
start_with_pause: true   # false for continuous time image sequence, and true for others, pause 'space' to shift mode
