# detect params
confidence_thres: 0.4
nms_thres: 0.3
device: 'gpu'  # cpu
auto_choose_device: true
input_size: 640
fp16: false

# weight file

weight_size: 's'  # m,l,x,tiny
model_path: './yolox-s.pth'
is_trt_file: false
classes_file: './coco_classes.txt'

# input source

source: '/home/lsh/Videos/test.avi'        #  0      'assets/dog.jpg'   '/path/to/your/image_dir'
source_type: 'vid'        # 'cam'   'image'            'image_dir'
save_image: false
show_image: true
start_with_pause: false   # false for continuous time image sequence, and true for others, pause 'space' to shift mode
