warmup_epochs: 5
warmup_lr: 0
basic_lr_per_img: 0.00015625   # 0.01 / 64
scheduler: "yoloxwarmcos"
no_aug_epochs: 15
min_lr_ratio: 0.05
ema: true

weight_decay: 0.0005
momentum: 0.9
print_interval: 10
eval_interval: 10